package marmot.type;

/**
 * 
 * @author Kang-Woo Lee (ETRI)
 */
public enum TypeCode {
	BYTE, SHORT, INT, LONG, FLOAT, DOUBLE, BOOLEAN, STRING, BINARY,
	TYPED, RESERVED01, RESERVED02, RESERVED03, RESERVED04,
	DATETIME, DATE, TIME, DURATION, INTERVAL,
	RESERVED10, RESERVED11, RESERVED12, RESERVED13, RESERVED14,
	ENVELOPE, TILE, GRID_CELL,
	RESERVED20, RESERVED21, RESERVED22, RESERVED23,
	POINT, MULTI_POINT, LINESTRING, MULTI_LINESTRING, POLYGON, MULTI_POLYGON, GEOM_COLLECTION, GEOMETRY,
	RESERVED30, RESERVED31, RESERVED32, RESERVED33, RESERVED34,
	TRAJECTORY;
	
	public int get() {
		return ordinal();
	}
	
	public static TypeCode fromCode(int code) {
		return values()[code];
	}
}